// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Provider } from 'react-redux';

// import rootReducer  from '../lib/store';

// import { Toaster } from 'react-hot-toast';
// import AppInitializer from '../lib/AppInitializer';
// import { configureStore } from "@reduxjs/toolkit";

// const store = configureStore({
//   reducer: rootReducer,
// });

// // import '../styles/globals.css';
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Task Management App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >

//         {/* {children} */}
//         <Provider store={store}>
//         <AppInitializer />
//           {children}
//           <Toaster />
//         </Provider>

//       </body>
//     </html>
//   );
// }




// ----
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/lib/ReduxProvider";
import { Toaster } from "react-hot-toast";
import AppInitializer from "@/lib/AppInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Task Management App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      {/* {children} */}
      
        {/* Wrap client-side dependencies in ReduxProvider */}
        <ReduxProvider>
          <AppInitializer />
          {children}
          <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
